# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""The `web` operation: start the kernel's HTTP listener and hand back its URL."""

import re
import subprocess
import sys
from typing import Any
from urllib.parse import urlsplit

from pydantic import BaseModel

from .types import Context, Operation

SERVING = re.compile(r"Serving MCP streamable HTTP on (\S+)")


class WebInput(BaseModel):
    pass


class WebOutput(BaseModel):
    url: str


def web(arguments: WebInput, context: Context) -> WebOutput:
    child: Any = subprocess.Popen(
        [sys.executable, "-m", f"{__package__}.mcp", "--http", "0", "--open"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
        # The listener outlives this call, and this process: an operation may not hold a socket.
        start_new_session=True,
    )
    for line in child.stderr:
        found = SERVING.search(line)
        if found:
            served = urlsplit(found.group(1))
            # The page, not the endpoint, and without the token the child already handed the
            # browser: an operation's result travels through an agent, and a token is a credential.
            return WebOutput(url=f"{served.scheme}://{served.netloc}/")
    raise RuntimeError("the kernel exited before it started serving")


OPERATION = Operation(
    name="web",
    description=(
        "Open this tool's web app: serves the operations page and the MCP endpoint on a free "
        "local port, opens a browser there, and returns the URL."
    ),
    input=WebInput,
    output=WebOutput,
    requires=("shell", "net"),
    annotations={"openWorldHint": False},
    handler=web,
)
