// tf:entry
// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { Type } from "typebox";

const entry = defineToolPlugin({
  id: "papervizagent-codex",
  name: "Papervizagent Codex",
  description: "Scientific figures with upstream PaperVizAgent, separate roles, configurable model providers and Codex subscription fallback. Host-native defaults where tools are available.",
  activation: {
    "onStartup": true
  },
  configSchema: Type.Unsafe<Record<string, unknown>>({
    "type": "object",
    "properties": {
      "papervizagent_codex_config": {
        "type": "string",
        "description": "Optional path to shared PaperVizAgent JSON/YAML model and pipeline configuration."
      },
      "codex_oauth_token": {
        "type": "string",
        "description": "Optional externally supplied Codex OAuth access token. Existing Codex sign-in is used when omitted.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "codex_account_id": {
        "type": "string",
        "description": "Optional account ID for an external token whose JWT does not contain it."
      },
      "google_api_key": {
        "type": "string",
        "description": "Optional Gemini API key.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "openai_api_key": {
        "type": "string",
        "description": "Optional OpenAI API key, separate from Codex OAuth.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "anthropic_api_key": {
        "type": "string",
        "description": "Optional Anthropic API key.",
        "x-toolfactory": {
          "sensitive": true
        }
      }
    }
  }),
  tools: () => [],
});

// /tf:entry

export default entry;
