// tf:entry
// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { join } from "node:path";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { resolveStateDir } from "openclaw/plugin-sdk/state-paths";
import { Type } from "typebox";

/**
 * Where this tool may keep its own state: OpenClaw's state directory, one folder per plugin.
 * Lazy, so that importing this module resolves no path and touches no disk — every host loader
 * and `plugin-inspector check --runtime` import the entry long before any tool runs.
 */
const dataDir = () => join(resolveStateDir(), "plugin-data", "papervizagent");

const execFileAsync = promisify(execFile);

const repoRoot =
  process.env["PAPERVIZAGENT_ROOT"] ?? fileURLToPath(new URL("../../../", import.meta.url));

/**
 * Shim variant: the core is Python, so every call crosses a process boundary and config
 * travels as environment, exactly as it does for the CLI and the MCP server.
 */
async function kernel(name: string, params: unknown, config: unknown): Promise<unknown> {
  const env: Record<string, string> = { ...(process.env as Record<string, string>) };
  for (const [key, value] of Object.entries((config ?? {}) as Record<string, unknown>)) {
    if (value !== undefined && value !== null) env[key.toUpperCase().replace(/[^A-Z0-9]/g, "_")] = String(value);
  }
  env["PAPERVIZAGENT_DATA_DIR"] = dataDir();
  const { stdout } = await execFileAsync(
    "uv",
    ["run", "python", "-m", "papervizagent.toolfactory.cli", name, "--json", JSON.stringify(params)],
    { cwd: repoRoot, env },
  );
  return JSON.parse(stdout) as unknown;
}

const entry = defineToolPlugin({
  id: "papervizagent",
  name: "Papervizagent",
  description: "Scientific figures with upstream PaperVizAgent, separate roles, configurable model providers and Codex subscription fallback. Host-native defaults where tools are available.",
  activation: {
    "onStartup": true
  },
  configSchema: Type.Unsafe<Record<string, unknown>>({
    "type": "object",
    "properties": {
      "papervizagent_config": {
        "type": "string",
        "description": "Optional path to shared PaperVizAgent JSON/YAML model and pipeline configuration."
      },
      "codex_oauth_token": {
        "type": "string",
        "description": "Optional externally supplied Codex OAuth access token. Existing Codex sign-in is used when omitted.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "codex_account_id": {
        "type": "string",
        "description": "Optional account ID for an external token whose JWT does not contain it."
      },
      "google_api_key": {
        "type": "string",
        "description": "Optional Gemini API key.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "openai_api_key": {
        "type": "string",
        "description": "Optional OpenAI API key, separate from Codex OAuth.",
        "x-toolfactory": {
          "sensitive": true
        }
      },
      "anthropic_api_key": {
        "type": "string",
        "description": "Optional Anthropic API key.",
        "x-toolfactory": {
          "sensitive": true
        }
      }
    }
  }),
  tools: (tool) => [
    tool({
      name: "generate",
      description: "Run upstream PaperVizAgent end to end, with configurable roles, modes, retrieval, candidates and critic rounds. Plot mode executes generated Python in a bounded subprocess.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "data": {
            "additionalProperties": true,
            "description": "Upstream input dictionary, including content and visual_intent; polish accepts its upstream image fields.",
            "title": "Data",
            "type": "object"
          },
          "settings": {
            "additionalProperties": true,
            "description": "Upstream pipeline settings; overrides the configuration file pipeline section. No credentials.",
            "title": "Settings",
            "type": "object"
          },
          "num_candidates": {
            "anyOf": [
              {
                "minimum": 1,
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "description": "Defaults to pipeline.num_candidates or 1.",
            "title": "Num Candidates"
          },
          "max_concurrent": {
            "anyOf": [
              {
                "minimum": 1,
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "description": "Defaults to pipeline.max_concurrent or 4.",
            "title": "Max Concurrent"
          }
        },
        "required": [
          "data"
        ],
        "title": "generateArguments"
      }),
      execute: async (params, config) => kernel("generate", params, config),
    }),
    tool({
      name: "infer",
      description: "Run one isolated PaperVizAgent role using its configured provider or Codex fallback. Returns text or an image file and request trace.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "role": {
            "enum": [
              "retriever",
              "planner",
              "stylist",
              "visualizer",
              "critic",
              "vanilla",
              "polish"
            ],
            "title": "Role",
            "type": "string"
          },
          "modality": {
            "enum": [
              "llm",
              "vlm",
              "image"
            ],
            "title": "Modality",
            "type": "string"
          },
          "system": {
            "default": "",
            "title": "System",
            "type": "string"
          },
          "contents": {
            "items": {
              "additionalProperties": true,
              "type": "object"
            },
            "title": "Contents",
            "type": "array"
          },
          "contents_file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "description": "Optional local JSON file containing content blocks, useful for image handoffs.",
            "title": "Contents File"
          },
          "options": {
            "additionalProperties": true,
            "title": "Options",
            "type": "object"
          }
        },
        "required": [
          "role",
          "modality"
        ],
        "title": "inferArguments"
      }),
      execute: async (params, config) => kernel("infer", params, config),
    }),
    tool({
      name: "models",
      description: "Read models and capabilities available through the configured Codex subscription. No inference.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {},
        "title": "modelsArguments"
      }),
      execute: async (params, config) => kernel("models", params, config),
    }),
    tool({
      name: "status",
      description: "Resolve per-role model routing using optional configuration and verified host capabilities. Does not call a model.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "native": {
            "description": "Capabilities verified by the calling host; never inferred from the host name.",
            "items": {
              "enum": [
                "llm",
                "vlm",
                "image"
              ],
              "type": "string"
            },
            "title": "Native",
            "type": "array"
          }
        },
        "title": "statusArguments"
      }),
      execute: async (params, config) => kernel("status", params, config),
    }),
    tool({
      name: "web",
      description: "Open this tool's web app: serves the operations page and the MCP endpoint on a free local port, opens a browser there, and returns the URL.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {},
        "title": "webArguments"
      }),
      execute: async (params, config) => kernel("web", params, config),
    }),
  ],
});

// /tf:entry

export default entry;
