# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""Hermes plugin for papervizagent-codex, registered through PluginContext.

Every handler returns a JSON string and never raises: Hermes dispatches tool
calls without a guard of its own, so an exception here escapes into the turn.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import os
from typing import Any, Callable

from papervizagent_codex.ops import OPERATIONS
from papervizagent_codex.toolfactory.config import context
from pydantic import BaseModel

TOOLSET = "papervizagent_codex"
REQUIRES_ENV = []
TOOLS = json.loads(
    r"""[]"""
)


def _ready() -> bool:
    """Hermes gates dispatch on this: every declared credential has to be present."""
    return all(os.environ.get(name) for name in REQUIRES_ENV)


def _operation(name: str) -> Any:
    """Fail loudly if the core package and this plugin disagree on the operations."""
    for operation in OPERATIONS:
        if operation.name == name:
            return operation
    raise LookupError(f"operation {name} is missing from the core package")


def _handler(name: str) -> Callable[..., str]:
    operation = _operation(name)

    def call(args: dict, **_kwargs: Any) -> str:
        try:
            result = operation.handler(operation.input(**args), context())
            if inspect.isawaitable(result):
                result = asyncio.run(result)
            if isinstance(result, BaseModel):
                result = result.model_dump(mode="json")
            return json.dumps(result, default=str)
        except Exception as exc:
            return json.dumps({"error": str(exc)})

    call.__name__ = f"{name}_handler"
    return call


def register(ctx: Any) -> None:
    # Hermes' own per-plugin data directory, through the variable every host uses.
    os.environ.setdefault("PAPERVIZAGENT_CODEX_DATA_DIR", str(ctx.state.data_dir))
    for schema in TOOLS:
        ctx.register_tool(
            name=schema["name"],
            toolset=TOOLSET,
            schema=schema,
            handler=_handler(schema["name"]),
            check_fn=_ready,
            requires_env=list(REQUIRES_ENV),
            description=schema["description"],
        )
