# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""The kernel CLI: one subcommand per operation, built from its input model's schema."""

import argparse
import asyncio
import inspect
import json
from typing import Any

from pydantic import BaseModel

from ..ops import OPERATIONS as AUTHORED_OPERATIONS
from .types import serves
from .config import context
from .web import OPERATION as WEB_OPERATION

#: The authored operations plus the generated `web` one, exactly as the MCP kernel lists them.
OPERATIONS = [*AUTHORED_OPERATIONS, WEB_OPERATION]


def kind(schema: dict[str, Any]) -> str:
    """The JSON Schema type of a property, looking through the optional/nullable union."""
    if "type" in schema:
        return str(schema["type"])
    for variant in schema.get("anyOf", []):
        if variant.get("type") not in (None, "null"):
            return str(variant["type"])
    return "string"


def coerce(value: str, of: str) -> Any:
    if of in ("integer", "number"):
        return int(value) if of == "integer" else float(value)
    if of == "array":
        return [item.strip() for item in value.split(",") if item.strip()]
    if of == "object":
        return json.loads(value)
    return value


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(
        prog="papervizagent-codex",
        description="Scientific figures with upstream PaperVizAgent, separate roles, configurable model providers and Codex subscription fallback. Host-native defaults where tools are available.",
    )
    subcommands = root.add_subparsers(dest="tf_command", required=True)
    for operation in OPERATIONS:
        if not serves(operation, "cli"):
            continue
        schema = operation.input.model_json_schema()
        command = subcommands.add_parser(operation.name, help=operation.description)
        command.add_argument(
            "--json", dest="tf_json", metavar="JSON", help="all arguments as one JSON object"
        )
        for name, property in (schema.get("properties") or {}).items():
            of = kind(property)
            hint = {"array": " (comma-separated)", "object": " (JSON)"}.get(of, "")
            help_text = f"{property.get('description', name)}{hint}"
            if of == "boolean":
                command.add_argument(f"--{name}", action="store_true", default=None, help=help_text)
            else:
                command.add_argument(f"--{name}", metavar="VALUE", help=help_text)
        command.set_defaults(tf_operation=operation, tf_schema=schema)

    mcp = subcommands.add_parser(
        "mcp", help="Serve the operations as an MCP server over stdio, or over streamable HTTP with --http"
    )
    mcp.add_argument(
        "--http",
        nargs="?",
        const=3000,
        type=int,
        default=None,
        metavar="PORT",
        help="serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
    )
    mcp.add_argument(
        "--pair",
        action="store_true",
        help="serve over HTTP with a fresh pairing token: prints <url>#<token> and requires it as a bearer token",
    )
    mcp.add_argument(
        "--open",
        action="store_true",
        help="serve over HTTP and open the web app in this machine's browser",
    )
    mcp.set_defaults(tf_operation=None, tf_schema={})
    return root


def main(argv: list[str] | None = None) -> None:
    options = parser().parse_args(argv)
    if options.tf_operation is None:
        if options.http is not None or options.pair or options.open:
            from .mcp import serve_http

            serve_http(port=3000 if options.http is None else options.http, pair=options.pair, open_browser=options.open)
        else:
            from .mcp import serve

            serve()
        return
    operation = options.tf_operation
    properties: dict[str, Any] = options.tf_schema.get("properties") or {}
    values: dict[str, Any] = json.loads(options.tf_json) if options.tf_json else {}
    for name, property in properties.items():
        given = getattr(options, name, None)
        if given is not None:
            values[name] = given if isinstance(given, bool) else coerce(given, kind(property))
    result = operation.handler(operation.input(**values), context())
    if inspect.isawaitable(result):
        result = asyncio.run(result)
    payload = result.model_dump(mode="json") if isinstance(result, BaseModel) else result
    print(json.dumps(payload, indent=2, default=str))


if __name__ == "__main__":
    main()
