# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""Configuration is read from the environment; hosts inject it from their own settings UI."""

import os
from pathlib import Path

from .types import Context


def data_dir() -> Path:
    """Where this tool may keep its own state: PAPERVIZAGENT_CODEX_DATA_DIR when a host sets it, else the
    platform's own data location (XDG on POSIX, %LOCALAPPDATA% on Windows)."""
    # Hosts that launch the kernel export their own name for it: Agent Plugins clients and
    # OpenClaw set PLUGIN_DATA, Claude Code sets CLAUDE_PLUGIN_DATA.
    configured = (
        os.environ.get("PAPERVIZAGENT_CODEX_DATA_DIR")
        or os.environ.get("PLUGIN_DATA")
        or os.environ.get("CLAUDE_PLUGIN_DATA")
    )
    if configured:
        return Path(configured)
    if os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA") or Path.home() / "AppData" / "Local")
    else:
        base = Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")
    return base / "papervizagent-codex"


def context() -> Context:
    return Context(config={
            "papervizagent_codex_config": os.environ.get("PAPERVIZAGENT_CODEX_CONFIG"),
            "codex_oauth_token": os.environ.get("CODEX_OAUTH_TOKEN"),
            "codex_account_id": os.environ.get("CODEX_ACCOUNT_ID"),
            "google_api_key": os.environ.get("GOOGLE_API_KEY"),
            "openai_api_key": os.environ.get("OPENAI_API_KEY"),
            "anthropic_api_key": os.environ.get("ANTHROPIC_API_KEY"),
        }, data_dir=data_dir())
