# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""The kernel MCP server: every operation registered from its pydantic input model.

Serves over stdio by default; `serve_http()` (or the CLI's `mcp --http [port]`) serves the
same server over MCP streamable HTTP instead: one Starlette app — the SDK's own streamable-HTTP
route, the built web app and `/env` — under uvicorn.
The page is served beside the endpoint so it POSTs same-origin, and `--open` is the whole launch.
"""

import argparse
import hashlib
import hmac
import inspect
import os
import secrets
import sys
import webbrowser
from pathlib import Path
from typing import Annotated, Any

from mcp.server.mcpserver import MCPServer
from starlette.responses import JSONResponse, PlainTextResponse
from starlette.routing import Mount, Route
from starlette.staticfiles import StaticFiles

from ..ops import OPERATIONS as AUTHORED_OPERATIONS
from .config import context, data_dir
from .types import Operation, serves
from .web import OPERATION as WEB_OPERATION

#: The authored operations plus the generated `web` one; `introspect` snapshots this list.
OPERATIONS = [*AUTHORED_OPERATIONS, WEB_OPERATION]

server = MCPServer(
    name="papervizagent-codex",
    version="0.3.0",
    description="Scientific figures with upstream PaperVizAgent, separate roles, configurable model providers and Codex subscription fallback. Host-native defaults where tools are available.",
)


def bind(operation: Operation) -> Any:
    """Give the handler the signature of its input model, so the SDK publishes that schema."""
    parameters = [
        inspect.Parameter(
            name,
            inspect.Parameter.KEYWORD_ONLY,
            annotation=Annotated[spec.annotation, spec],
            default=inspect.Parameter.empty if spec.is_required() else spec.default,
        )
        for name, spec in operation.input.model_fields.items()
    ]

    async def call(**arguments: Any) -> Any:
        result = operation.handler(operation.input(**arguments), context())
        return await result if inspect.isawaitable(result) else result

    call.__name__ = operation.name
    call.__signature__ = inspect.Signature(
        parameters,
        return_annotation=operation.output if operation.output else inspect.Signature.empty,
    )
    return call


#: toolfactory introspects with every operation visible; a served instance lists only what MCP can run.
INTROSPECTING = bool(os.environ.get("TOOLFACTORY_INTROSPECT"))

for operation in OPERATIONS:
    if not INTROSPECTING and not serves(operation, "mcp"):
        continue
    server.add_tool(
        bind(operation),
        name=operation.name,
        description=operation.description,
        annotations=operation.annotations or None,
        meta={"dev.toolfactory": {"requires": list(operation.requires)}},
    )


def serve() -> None:
    server.run("stdio")


#: The pairing token, so a browser extension (or anything else on loopback) can prove it is the
#: client the user paired: the endpoint requires `Authorization: Bearer <token>` when
#: PAPERVIZAGENT_CODEX_MCP_TOKEN is set or `mcp --http --pair` has written one under the data directory. With
#: neither, nothing changes and the endpoint stays open on loopback.
TOKEN_FILE = "relay-token"


def token_path() -> Path:
    return data_dir() / TOKEN_FILE


def paired_token() -> str | None:
    configured = os.environ.get("PAPERVIZAGENT_CODEX_MCP_TOKEN")
    if configured:
        return configured
    try:
        return token_path().read_text().strip() or None
    except OSError:
        return None


def mint_token() -> str:
    """Mint a token and keep it 0600 under the data directory. Never rotates an existing one."""
    token = secrets.token_urlsafe(32)
    path = token_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{token}\n")
    path.chmod(0o600)
    return token


def guard(app: Any, token: str, paths: "set[str]") -> Any:
    """Wrap the ASGI app: no `Authorization: Bearer <token>`, no request — on the API paths only.
    The page itself is never guarded: a browser cannot put a header on its own document request."""
    expected = hashlib.sha256(token.encode()).digest()

    async def guarded(scope: Any, receive: Any, send: Any) -> None:
        if scope["type"] == "http" and scope["path"] in paths:
            presented = dict(scope["headers"]).get(b"authorization", b"").removeprefix(b"Bearer ")
            if not hmac.compare_digest(hashlib.sha256(presented).digest(), expected):
                await send(
                    {
                        "type": "http.response.start",
                        "status": 401,
                        "headers": [(b"www-authenticate", b"Bearer")],
                    }
                )
                await send({"type": "http.response.body", "body": b""})
                return
        await app(scope, receive, send)

    return guarded


def web_dist() -> "Path | None":
    """The wheel maps `web/dist` here at package time; a checkout has it in place."""
    package = Path(__file__).resolve().parent.parent
    for candidate in (package / "web", package.parent.parent / "web" / "dist"):
        if candidate.is_dir():
            return candidate
    return None


def web_route() -> "Mount | Route":
    """Everything that is not an API route is the page, or the hint that it was never built."""
    directory = web_dist()
    if directory is not None:
        return Mount("/", app=StaticFiles(directory=directory, html=True))

    async def missing(request: Any) -> PlainTextResponse:
        return PlainTextResponse("no web/dist; run `npm -C web run build`\n", status_code=404)

    return Route("/{path:path}", missing)


#: The names this project declares; `/env` writes no other.
SECRETS = ["CODEX_OAUTH_TOKEN","GOOGLE_API_KEY","OPENAI_API_KEY","ANTHROPIC_API_KEY","NPM_TOKEN","CLAWHUB_TOKEN","CHROME_EXTENSION_ID","CHROME_PUBLISHER_ID","CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL","CHROME_SERVICE_ACCOUNT_PRIVATE_KEY","FIREFOX_EXTENSION_ID","FIREFOX_JWT_ISSUER","FIREFOX_JWT_SECRET","EDGE_PRODUCT_ID","EDGE_CLIENT_ID","EDGE_API_KEY"]


def env_path() -> Path:
    return Path.cwd() / ".env"


def env_lines() -> "list[str]":
    try:
        return env_path().read_text().rstrip("\n").split("\n")
    except OSError:
        return []


def env_present() -> "list[str]":
    """Which declared names `.env` already carries a value for. Names only — never a value."""
    found = {}
    for line in env_lines():
        name, _, value = line.lstrip().removeprefix("export ").partition("=")
        if value.strip():
            found[name.strip()] = True
    return [name for name in SECRETS if name in found]


def env_write(name: str, value: str) -> None:
    """Rewrite one line of `.env`, keeping every other line, and keep the file private."""
    lines = env_lines()
    for index, line in enumerate(lines):
        if line.lstrip().removeprefix("export ").partition("=")[0].strip() == name:
            lines[index] = f"{name}={value}"
            break
    else:
        lines.append(f"{name}={value}")
    env_path().write_text("\n".join(lines) + "\n")
    env_path().chmod(0o600)
    # The name, never the value: this log is the one place a secret could leak by accident.
    print(f".env: set {name}", file=sys.stderr, flush=True)


def env_route(token: "str | None") -> Route:
    """`GET` the names present, `POST {name, value}` one of them. Writing needs the bearer token."""

    async def endpoint(request: Any) -> JSONResponse:
        # Names, never values: what this project declares and which `.env` already carries.
        if request.method == "GET":
            return JSONResponse({"declared": SECRETS, "present": env_present()})
        # Even on loopback: without a token in force there is no client to trust with a write.
        if token is None:
            return JSONResponse({"error": "unpaired: restart with `mcp --http --open`"}, status_code=403)
        try:
            payload = await request.json()
            name, value = payload["name"], payload["value"]
        except Exception:
            return JSONResponse({"error": "expected {name, value}"}, status_code=400)
        if name not in SECRETS:
            return JSONResponse({"error": "not a declared secret"}, status_code=400)
        if not isinstance(value, str) or not value:
            return JSONResponse({"error": "empty value"}, status_code=400)
        env_write(name, value)
        return JSONResponse({"declared": SECRETS, "present": env_present()})

    return Route("/env", endpoint, methods=["GET", "POST"])


def serve_http(
    host: str = "127.0.0.1",
    port: int = 3000,
    path: str = "/mcp",
    pair: bool = False,
    open_browser: bool = False,
) -> None:
    """Serve over MCP streamable HTTP instead of stdio. Opt-in; stdio stays the default transport."""
    import uvicorn

    # `--open` needs a token for the page to call back with; an existing one is never rotated,
    # because the browser extension holds it.
    token = mint_token() if pair else (paired_token() or (mint_token() if open_browser else None))
    # One ASGI app: the SDK's own streamable-HTTP route (its session-manager lifespan with it),
    # plus ours. Appending to its router is what keeps that lifespan the app's own.
    app = server.streamable_http_app(streamable_http_path=path, stateless_http=True, host=host)
    app.router.routes.append(env_route(token))
    app.router.routes.append(web_route())
    if token is not None:
        app = guard(app, token, {path, "/env"})
    config = uvicorn.Config(app, host=host, port=port, log_level="warning")
    # Bind before serving: `--http 0` asks the OS for a free port and the URL is only known then.
    sock = config.bind_socket()
    base = f"http://{host}:{sock.getsockname()[1]}"
    if pair:
        print(f"{base}{path}#{token}", flush=True)
    suffix = " (bearer token required)" if token else ""
    print(f"Serving MCP streamable HTTP on {base}{path}{suffix}", file=sys.stderr, flush=True)
    if open_browser:
        webbrowser.open(f"{base}/#{token}")
    uvicorn.Server(config).run(sockets=[sock])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--http",
        nargs="?",
        const=3000,
        type=int,
        default=None,
        metavar="PORT",
        help="serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
    )
    parser.add_argument(
        "--pair",
        action="store_true",
        help="serve over HTTP with a fresh pairing token: prints <url>#<token> and requires it as a bearer token",
    )
    parser.add_argument(
        "--open",
        action="store_true",
        help="serve over HTTP and open the web app in this machine's browser",
    )
    args = parser.parse_args()
    if args.http is None and not args.pair and not args.open:
        serve()
    else:
        # `--http 0` is a port, not a missing one: only `None` means "use the default".
        serve_http(port=3000 if args.http is None else args.http, pair=args.pair, open_browser=args.open)


if __name__ == "__main__":
    main()
