# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""The operation contract: what an entry in `OPERATIONS` looks like."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel

#: Host capabilities an operation may declare. Portable: net, fs, shell, secret.
Capability = Literal["net", "fs", "shell", "secret", "browser", "model", "user-input", "channel"]


@dataclass(frozen=True)
class Context:
    """Configuration read from the environment, keyed as declared in dev.toolfactory/tool.json."""

    config: dict[str, str | None]
    #: Directory this tool may keep its own state in. Created by the tool, not by the kernel.
    data_dir: Path


@dataclass(frozen=True)
class Operation:
    """One operation: a pure function of (arguments, context.config, filesystem)."""

    name: str
    description: str
    input: type[BaseModel]
    handler: Callable[[Any, Context], Any]
    output: type[BaseModel] | None = None
    requires: tuple[Capability, ...] = ()
    annotations: dict[str, bool] = field(default_factory=dict)

#: Capabilities every surface can satisfy on its own.
PORTABLE: frozenset[str] = frozenset({"net", "fs", "shell", "secret"})


def serves(operation: "Operation", surface: Literal["mcp", "cli"]) -> bool:
    """Whether a surface can run an operation: MCP needs a portable one; a CLI also has a human for user-input."""
    return all(c in PORTABLE or (surface == "cli" and c == "user-input") for c in operation.requires)
